### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Noname400** [AlexCurl/BTC-Python-Webserver#1]
hi
not work http://176.57.215.247:3333/
[ previous | next | random ]   <=>   [ first | middle | last ]

**Comment by AlexCurl** [comment]
i use it locally on desktop computer. you probably trying to set it up on remote server?

**Comment by Noname400** [comment]
Yes.
Help

**Comment by AlexCurl** [comment]
<<<<<<< HEAD:webserver_5.1.8.py
    else {$('#all_num').html(128);}          
=======
    else {$('#all_num').html(128);}
>>>>>>> 0e40d40430320b962152a19a28e10a9421261d87:webserver_5.1.7.py

How this got into code? This is the problem.
