### ISSUE TITLE
Page 1

### ISSUE THREAD

**Issue by Alf71** [AlexCurl/BTC-Python-Webserver#3]
I have run this for several hours. Now I wanted to change to sequence from a given hexadecimal value. It is not working.
Also if I click page 1, it is showing mixed keys and not sequential.

![grafik](https://user-images.githubusercontent.com/7470579/192091554-268c5925-86e5-48ad-b66b-c53169296c30.png)

**Comment by AlexCurl** [comment]
If you start randomG this will be like that - mixed keys. In secp256k1 curve any point can be a generator and its privatekey will be an "increment step" mod N(order of the group). If you take 2G for example you will have keys 2,4,6,8 and so on. If you take 3G you will have 3,6,9 and so on. Now will explain what it might be useful for. First off if you search for ways to get private key from public(ECDSA decreation). We already know there is exactly one straightforward way to do it. Divide by 2 and subtract G(one). But this method requires to know whether point is even or odd in terms of its position in a subgroup. Not yet solved.
Second if you just search might shift some key in new position. Maybe even closer to start of the range.

**Comment by Alf71** [comment]
"But this method requires to know whether point is even or odd in terms of its position in a subgroup. Not yet solved."

If one solve this, the whole addresses with known pubkeys would be exposed...

**Comment by AlexCurl** [comment]
Yes. And more. Transaction change also since you will get private key for ECDSA signature.

**Comment by Alf71** [comment]
Ah, interesting theory.

**Comment by AlexCurl** [comment]
If you wanna discuss or work also in in that write to me on telegram.
